# Generated by Django 2.2.24 on 2021-09-03 04:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210903_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 4, 24, 3, 83066, tzinfo=utc)),
        ),
    ]
